#! /bin/sh

### Bspwm Config ###

# Workspaces
bspc monitor -d 1 2 3 4 5

# Window Settings
wmname LG3D

bspc config border_width 	      0
bspc config window_gap            15

# Colors 
bspc config focused_border_color  #ce72a1
bspc config normal_border_color   #ce72a1
bspc config presel_feedback_color $(xgetres background)

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true


### Autostart Apps ###

# Wallpaper
feh --no-fehbg --bg-fill '/home/billy/Pictures/Wallpapers/wall.png' & 

# Refresh Rate
xrandr --output DP-4 --mode '1920x1080' --rate '165'

# Key Daemon
sxhkd -c ~/.config/bspwm/sxhkdrc & 

# Polybar
~/.config/polybar/launch.sh &

# Dunst
~/.config/dunst/launch.sh &

# Power Manager
xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
hsetroot -solid $(xgetres background) &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &

# Load Bitmap Fonts
xset +fp ~/.local/share/fonts &
xset fp rehash &
xset fp+ /usr/share/fonts/bitmap &

# Phicom
picom &
